services:
   dev:
     build: .
     platform: linux/amd64
     ports:
       - "127.0.0.1:8081:8081"
     volumes:
       - ./keyrings:/home/node/.local/share/keyrings
       - ./config:/home/node/.snc
       - ./data:/home/node/data
